import { Navbar } from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Condensed } from 'next/font/google'
import { navbarItems } from '@/config/navbar'

const robotoCondensed = Roboto_Condensed({
  weight: ['300', '400', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <Navbar items={navbarItems}/>
        {children}
      </body>
    </html>
  )
}
